Move dracuf files to usr/lib dir
SUSE-Enceladus/amazon-dracut-config pull request #2
Opened 2024-12-04 20:32 UTC by smarlowucf

2024-12-05 10:01 UTC, apozsuse approved these changes
LGTM

2024-12-05 10:05 UTC, rjschwei requested changes

2024-12-05 10:05 UTC, rjschwei commented on amazon-dracut-config.spec
> +    %{buildroot}/usr/lib/dracut/dracut.conf.d/07-ext4.conf
Please use the `%_libdir` macro

2025-01-06 18:32 UTC, smarlowucf commented
Merged the config macro change and rebased

2025-01-07 19:23 UTC, smarlowucf commented
Fixed path using full path instead.

2025-01-07 20:37 UTC, rjschwei approved these changes

2025-01-07 21:35 UTC, jgleissner approved these changes

2025-01-08 16:05 UTC, merged